[package]
name = "bcc-rust"
version = "0.1.0"
edition = "2021"
description = "C99 Compliant C Compiler"
license-file = "LICENSE"
readme = "README.md"
keywords = ["compiler", "C", "C-compiler"]
categories = ["command-line-utilities", "development-tools", "compilers"]
repository = "https://www.github.com/bwallker/bcc-rust"
rust-version = "1.81.0"

[features]
benchmarking-internals = []

[profile.release]
lto = "fat"
debug = "full"
codegen-units = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lints.clippy]
# Enabled lints from the 'Restrictions' group
# Sadly we cannot used "forbid" here because it breaks clap since its macro expansions include a blanket #[allow(clippy::restriction].
allow-attributes = "warn"
allow-attributes-without-reason = "warn"
assertions-on-result-states = "warn"
assigning_clones = "warn"
empty-drop = "warn"
empty-enum-variants-with-brackets = "warn"
empty-struct-with-brackets = "warn"
fn-to-numberic-cast-any = "warn"
format-push-string = "warn"
if-then-some-else-none = "warn"
infinite-loop = "warn"
large-include-file = "warn"
missing-assert-message = "warn"
mod-module-files = "deny"
multiple-unsafe-ops-per-block = "deny"
partial-pub-fields = "warn"
pub-without-shorthand = "warn"
rc-mutex = "warn"
redundant-type-annotations = "warn"
renamed-function-params = "warn"
same-name-method = "warn"
semicolon-inside-block = "warn"
string-lit-chars-any = "warn"
suspicous-xor-used-as-pow = "warn"
test-outside-test-module = "warn"
undocumented-unsafe-blocks = "deny"
unnecessary-safety-comment = "deny"
unnecessary-safety-doc = "deny"
unnecessary-self-imports = "warn"

cargo = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
cast-possible-wrap = "allow"
cast-sign-loss = "allow"
inline-always = "allow"
perf = { level = "warn", priority = -1 }


# Enable provenance lints when strict provenance is stable
# Enable must-not-suspend and nont-exhaustive-omitted-patterns when they are stable
[lints.rust]
absolute-paths-not-starting-with-crate = "forbid"
elided-lifetimes-in-paths = "warn"
explicit-outlives-requirements = "warn"
# fuzzy-provenance-casts = "forbid"
let-underscore-drop = "warn"
# lossy-provenance-casts = "forbid"
macro-use-extern-crate = "warn"
missing-abi = "forbid"
missing-debug-implementations = "warn"
missing-docs = "warn"
# must-not-suspend = "forbid"
# non-exhaustive-omitted-patterns = "warn"
single-use-lifetimes = "warn"
trivial-casts = "warn"
trivial-numeric-casts = "warn"
unsafe-op-in-unsafe-fn = "forbid"
unused-crate-dependencies = "warn"
unused-extern-crates = "warn"
unused-import-braces = "warn"
unused-lifetimes = "warn"
unused-macro-rules = "warn"
unused-qualifications = "warn"
unused-results = "warn"
variant-size-differences = "warn"


[dependencies]
bitfield = "0.15.0"
chrono = "0.4.38"
clap = { version = "4.5.17", features = ["derive"] }
hashbrown = { version = "0.14.5", features = ["raw"] }
owo-colors = "4.0.0"
rustc-hash = "1.1.0"
smallstr = "0.3.0"
thiserror = "1.0.63"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
pretty_assertions = "1.4.0"
proptest = "1.5.0"
rstest = "0.20.0"

[build-dependencies]
bindgen = "0.69.4"
cc = "1.1.18"

[[bench]]
name = "bench"
harness = false
required-features = ["benchmarking-internals"]
