#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unreachable_pub,
    unused_results,
    clippy::all,
    clippy::allow_attributes,
    clippy::allow_attributes_without_reason,
    reason = "The included bindings are generated by bindgen."
)]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
